version: "3"

tasks:
  create:
    desc: create ollama-local pod
    cmds:
      - sh ./bin/create.sh
  remove:
    desc: remove ollama-local pod
    cmds:
      - sh ./bin/remove.sh
  ollama-tty:
    desc: ollama terminal
    cmds:
      - podman exec -it ollama /bin/bash
